;------------------------------------------------------------------------------
;-         ATMEL Microcontroller Software Support  -  ROUSSET  -
;------------------------------------------------------------------------------
; The software is delivered "AS IS" without warranty or condition of any
; kind, either express, implied or statutory. This includes without
; limitation any warranty or condition with respect to merchantability or
; fitness for any particular purpose, or against the infringements of
; intellectual property rights of others.
;------------------------------------------------------------------------------
;- File Name            : piob.inc
;- Object               : Assembler Parallel I/O Controller B Definition File.
;-
;- 1.0 01/04/00 JCZ     : Creation
;------------------------------------------------------------------------------

PB0             EQU     (1:SHL:0)
PB1             EQU     (1:SHL:1)
PB2             EQU     (1:SHL:2)
PB3             EQU     (1:SHL:3)
PB4             EQU     (1:SHL:4)
PB5             EQU     (1:SHL:5)
PB6             EQU     (1:SHL:6)
PB7             EQU     (1:SHL:7)
PB8             EQU     (1:SHL:8)
PB9             EQU     (1:SHL:9)
PB10            EQU     (1:SHL:10)
PB11            EQU     (1:SHL:11)
PB12            EQU     (1:SHL:12)
PB13            EQU     (1:SHL:13)
PB14            EQU     (1:SHL:14)
PB15            EQU     (1:SHL:15)
PB16            EQU     (1:SHL:16)
PB17            EQU     (1:SHL:17)
PB18            EQU     (1:SHL:18)
PB19            EQU     (1:SHL:19)
PB20            EQU     (1:SHL:20)
PB21            EQU     (1:SHL:21)
PB22            EQU     (1:SHL:22)
PB23            EQU     (1:SHL:23)
PB24            EQU     (1:SHL:24)
PB25            EQU     (1:SHL:25)
PB26            EQU     (1:SHL:26)
PB27            EQU     (1:SHL:27)

                END
