;------------------------------------------------------------------------------
;-         ATMEL Microcontroller Software Support  -  ROUSSET  -
;------------------------------------------------------------------------------
; The software is delivered "AS IS" without warranty or condition of any
; kind, either express, implied or statutory. This includes without
; limitation any warranty or condition with respect to merchantability or
; fitness for any particular purpose, or against the infringements of
; intellectual property rights of others.
;------------------------------------------------------------------------------
;- File Name            : pio.inc
;- Object               : Assembler Parallel I/O Controller Definition File.
;-
;- 1.0 01/04/00 JCZ     : Creation
;------------------------------------------------------------------------------

P0              EQU     (1:SHL:0)
P1              EQU     (1:SHL:1)
P2              EQU     (1:SHL:2)
P3              EQU     (1:SHL:3)
P4              EQU     (1:SHL:4)
P5              EQU     (1:SHL:5)
P6              EQU     (1:SHL:6)
P7              EQU     (1:SHL:7)
P8              EQU     (1:SHL:8)
P9              EQU     (1:SHL:9)
P10             EQU     (1:SHL:10)
P11             EQU     (1:SHL:11)
P12             EQU     (1:SHL:12)
P13             EQU     (1:SHL:13)
P14             EQU     (1:SHL:14)
P15             EQU     (1:SHL:15)
P16             EQU     (1:SHL:16)
P17             EQU     (1:SHL:17)
P18             EQU     (1:SHL:18)
P19             EQU     (1:SHL:19)
P20             EQU     (1:SHL:20)
P21             EQU     (1:SHL:21)
P22             EQU     (1:SHL:22)
P23             EQU     (1:SHL:23)
P24             EQU     (1:SHL:24)
P25             EQU     (1:SHL:25)
P26             EQU     (1:SHL:26)
P27             EQU     (1:SHL:27)
P28             EQU     (1:SHL:28)
P29             EQU     (1:SHL:29)
P30             EQU     (1:SHL:30)
P31             EQU     (1:SHL:31)

                END
