;------------------------------------------------------------------------------
;-         ATMEL Microcontroller Software Support  -  ROUSSET  -
;------------------------------------------------------------------------------
; The software is delivered "AS IS" without warranty or condition of any
; kind, either express, implied or statutory. This includes without
; limitation any warranty or condition with respect to merchantability or
; fitness for any particular purpose, or against the infringements of
; intellectual property rights of others.
;------------------------------------------------------------------------------
;- File Name            : pioa.inc
;- Object               : Assembler Parallel I/O Controller A Definition File.
;-
;- 1.0 01/04/00 JCZ     : Creation
;- 1.1 16/11/00 ED	: PA30 and PA31 added
;------------------------------------------------------------------------------

PA0             EQU     (1:SHL:0)
PA1             EQU     (1:SHL:1)
PA2             EQU     (1:SHL:2)
PA3             EQU     (1:SHL:3)
PA4             EQU     (1:SHL:4)
PA5             EQU     (1:SHL:5)
PA6             EQU     (1:SHL:6)
PA7             EQU     (1:SHL:7)
PA8             EQU     (1:SHL:8)
PA9             EQU     (1:SHL:9)
PA10            EQU     (1:SHL:10)
PA11            EQU     (1:SHL:11)
PA12            EQU     (1:SHL:12)
PA13            EQU     (1:SHL:13)
PA14            EQU     (1:SHL:14)
PA15            EQU     (1:SHL:15)
PA16            EQU     (1:SHL:16)
PA17            EQU     (1:SHL:17)
PA18            EQU     (1:SHL:18)
PA19            EQU     (1:SHL:19)
PA20            EQU     (1:SHL:20)
PA21            EQU     (1:SHL:21)
PA22            EQU     (1:SHL:22)
PA23            EQU     (1:SHL:23)
PA24            EQU     (1:SHL:24)
PA25            EQU     (1:SHL:25)
PA26            EQU     (1:SHL:26)
PA27            EQU     (1:SHL:27)
PA28            EQU     (1:SHL:28)
PA29            EQU     (1:SHL:29)
PA30            EQU     (1:SHL:30)
PA31            EQU     (1:SHL:31)

                END
